# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'animal.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_single = QtWidgets.QPushButton(Dialog)
        self.btn_single.setObjectName("btn_single")
        self.gridLayout.addWidget(self.btn_single, 0, 1, 1, 1)
        self.btn_batch = QtWidgets.QPushButton(Dialog)
        self.btn_batch.setObjectName("btn_batch")
        self.gridLayout.addWidget(self.btn_batch, 1, 1, 1, 1)
        self.btn_save = QtWidgets.QPushButton(Dialog)
        self.btn_save.setObjectName("btn_save")
        self.gridLayout.addWidget(self.btn_save, 2, 1, 1, 1)
        self.label_result = QtWidgets.QLabel(Dialog)
        self.label_result.setObjectName("label_result")
        self.gridLayout.addWidget(self.label_result, 3, 1, 1, 1)
        self.label_img = QtWidgets.QLabel(Dialog)
        self.label_img.setObjectName("label_img")
        self.gridLayout.addWidget(self.label_img, 1, 0, 3, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_single.setText(_translate("Dialog", "单张检测"))
        self.btn_batch.setText(_translate("Dialog", "批量检测"))
        self.btn_save.setText(_translate("Dialog", "保存图片"))
        self.label_result.setText(_translate("Dialog", "类别"))
        self.label_img.setText(_translate("Dialog", "图片"))
