# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit_log = QtWidgets.QTextEdit(Dialog)
        self.textEdit_log.setObjectName("textEdit_log")
        self.gridLayout.addWidget(self.textEdit_log, 10, 0, 1, 1)
        self.pushButton_pause_batch = QtWidgets.QPushButton(Dialog)
        self.pushButton_pause_batch.setObjectName("pushButton_pause_batch")
        self.gridLayout.addWidget(self.pushButton_pause_batch, 8, 1, 1, 1)
        self.pushButton_export = QtWidgets.QPushButton(Dialog)
        self.pushButton_export.setObjectName("pushButton_export")
        self.gridLayout.addWidget(self.pushButton_export, 5, 1, 1, 1)
        self.pushButton_saveimg = QtWidgets.QPushButton(Dialog)
        self.pushButton_saveimg.setObjectName("pushButton_saveimg")
        self.gridLayout.addWidget(self.pushButton_saveimg, 7, 1, 1, 1)
        self.pushButton_single = QtWidgets.QPushButton(Dialog)
        self.pushButton_single.setObjectName("pushButton_single")
        self.gridLayout.addWidget(self.pushButton_single, 2, 1, 1, 1)
        self.pushButton_clear = QtWidgets.QPushButton(Dialog)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.gridLayout.addWidget(self.pushButton_clear, 6, 1, 1, 1)
        self.pushButton_batch = QtWidgets.QPushButton(Dialog)
        self.pushButton_batch.setObjectName("pushButton_batch")
        self.gridLayout.addWidget(self.pushButton_batch, 3, 1, 1, 1)
        self.slider_conf = QtWidgets.QSlider(Dialog)
        self.slider_conf.setOrientation(QtCore.Qt.Horizontal)
        self.slider_conf.setObjectName("slider_conf")
        self.gridLayout.addWidget(self.slider_conf, 0, 0, 2, 1)
        self.label_slider_val = QtWidgets.QLabel(Dialog)
        self.label_slider_val.setObjectName("label_slider_val")
        self.gridLayout.addWidget(self.label_slider_val, 12, 0, 1, 1)
        self.label_picture = QtWidgets.QLabel(Dialog)
        self.label_picture.setObjectName("label_picture")
        self.gridLayout.addWidget(self.label_picture, 2, 0, 7, 1)
        self.pushButton_camera = QtWidgets.QPushButton(Dialog)
        self.pushButton_camera.setObjectName("pushButton_camera")
        self.gridLayout.addWidget(self.pushButton_camera, 4, 1, 1, 1)
        self.pushButton_train = QtWidgets.QPushButton(Dialog)
        self.pushButton_train.setObjectName("pushButton_train")
        self.gridLayout.addWidget(self.pushButton_train, 0, 1, 1, 1)
        self.pushButton_start_batch = QtWidgets.QPushButton(Dialog)
        self.pushButton_start_batch.setObjectName("pushButton_start_batch")
        self.gridLayout.addWidget(self.pushButton_start_batch, 9, 1, 1, 1)
        self.label_result = QtWidgets.QLabel(Dialog)
        self.label_result.setObjectName("label_result")
        self.gridLayout.addWidget(self.label_result, 10, 1, 1, 1)
        self.label_count = QtWidgets.QLabel(Dialog)
        self.label_count.setObjectName("label_count")
        self.gridLayout.addWidget(self.label_count, 12, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.textEdit_log.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">识别日志输出区</p></body></html>"))
        self.pushButton_pause_batch.setText(_translate("Dialog", "暂停"))
        self.pushButton_export.setText(_translate("Dialog", "导出识别报表"))
        self.pushButton_saveimg.setText(_translate("Dialog", "保存识别后图片"))
        self.pushButton_single.setText(_translate("Dialog", "单张图片动物识别"))
        self.pushButton_clear.setText(_translate("Dialog", "清空所有内容"))
        self.pushButton_batch.setText(_translate("Dialog", "批量文件夹分拣识别"))
        self.label_slider_val.setText(_translate("Dialog", "当前阈值："))
        self.label_picture.setText(_translate("Dialog", "在这里显示图片"))
        self.pushButton_camera.setText(_translate("Dialog", "摄像头实时检测"))
        self.pushButton_train.setText(_translate("Dialog", "训练动物检测模型"))
        self.pushButton_start_batch.setText(_translate("Dialog", "开始"))
        self.label_result.setText(_translate("Dialog", "识别结果"))
        self.label_count.setText(_translate("Dialog", "识别数量"))
